server:
  port: 8082
spring:
  application:
    name: customers
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://auth-server:9000
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery:8761/eureka
